/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.2
</auto-generated>
------------------------------------------------------------------------------ */
using System.Web;
using System.Web.Mvc;
using Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers.Attributes;
using Telerik.Sitefinity.Modules.Pages.Configuration;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Web;

namespace SitefinityWebApp.Mvc.Controllers
{
    [EnhanceViewEnginesAttribute]
    [ControllerToolboxItem(Name = "PageTilesWidget_MVC", Title = "PageTilesWidget", SectionName = ToolboxesConfig.ContentToolboxSectionName)]
    public class PageTilesWidgetController : Controller
	{
		// GET: PageTilesWidget
		public ActionResult Index()
		{
            SiteMapNodeCollection siteMapNodeCollection = null;

         var currentNode = SiteMapBase.GetActualCurrentNode();

            if (currentNode?.HasChildNodes ?? false)
            {
                siteMapNodeCollection = currentNode.ChildNodes;
            }
            return View(siteMapNodeCollection);
		}

	}
}